# Generated by Django 4.2.11 on 2025-08-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('army_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('enlistment_date', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='main.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('year_of_passing', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='main.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('date_awarded', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='main.officer')),
            ],
        ),
    ]
